id: a1b2c3d4-cloud-mock-hcsc-demo0000002
name: Cloud
values:
  - key: fhirBaseUrl
    value: 'https://825f1a38-58e2-45ba-ac0f-e5deee2a9ad4.mock.pstmn.io'
    enabled: true
    type: default
  - key: clientId
    value: demo-client-id
    enabled: true
    type: default
  - key: clientSecret
    value: demo-client-secret
    enabled: true
    type: secret
_postman_variable_scope: environment
