id: a1b2c3d4-local-4500-hcsc-demo0000001
name: Local
values:
  - key: fhirBaseUrl
    value: 'http://localhost:4500'
    enabled: true
    type: default
  - key: clientId
    value: test-client
    enabled: true
    type: default
  - key: clientSecret
    value: test-secret
    enabled: true
    type: secret
_postman_variable_scope: environment
